# This file should trigger gb-yaml-env-password
version: '3.8'
services:
  app:
    image: myapp
    environment:
      - DB_PASSWORD=MyYamlEnvPassword!@#
      - SECRET_TOKEN=another_yaml_env_secret_xyz789
# Should not trigger (placeholder)
#      - VAR_PASSWORD=${SOME_VAR}
